### PR TITLE
App Install in Magisk!

### PR DESCRIPTION
**Pull request by ghost**
I have modified the Magisk Module Template to allow app installation in /data /app together with module installation.
I think this feature is very useful for module developers
Operation is simple if the $DATAAPP variable in config.sh is true,  then the "data/app" folder of the module containing the apps to be installed is copied to /data /app and the right permissions are applied through "set_perm_recursive".
If the module is installed in bootmode (then from the magisk manager) the apps will be installed directly via "pm install" and then they will be accessible without restarting.
For module developers, just enable DATAAPP in config.sh and create a folder with a name that remembers the app to install with the apk file with the same name as the folder.

### CODE REVIEW

**Comment by ghost** [comment]
Update: 
Now while the phone is booted, apps will instantly install by "pm install"

**Comment by Dark1z** [comment]
I think that it would be better to make another template to Install Apps.   
You can all it something like : Magisk App-Install Template     
Your's is a good Idea and I like it very much, if you can kindly make it for more than 1 app.   
👍

**Comment by ghost** [comment]
@dark-1 
I did not understand this statement "if you can kindly make it for more than 1 app." My modification of course allows installing an infinite number of apps /date

**Comment by ghost** [comment]
Changelog:
-Applied to Magisk Module Template 4
-Resolved bootmode installation issues

**Comment by ghost** [comment]
Complete guide and technical explanation available at https://github.com/PurifyOS/magisk-module-template/blob/master/README.md
Translated in English and Italian

**Comment by Dark1z** [comment]
@ErnyTech ,
Sorry I did not read the whole code so must have missed.
BUT , did you considered making it as a different template instead of merging with the Original topjohnwu's template?
Best Regards. 👍

**Comment by ghost** [comment]
Yes look here: https://github.com/PurifyOS/magisk-module-template/blob/master/README.md

**Comment by Dark1z** [comment]
In that case , I thing you need Close this pull request as you won't be merging with topjohnwu's Original template.

👍

**Comment by ghost** [comment]
I would like to hear @topjohnwu's opinion

**Comment by topjohnwu** [comment]
Well, on Android O, the app installation location is different. That's why I had to install/upgrade Magisk Manager programmatically :)
I would consider add this natively into Magisk

**Comment by Dark1z** [comment]
Hmm... Nice 👍

**Comment by ghost** [comment]
Interesting ah, I will modify it to support Android O! thank you

**Comment by ErnyTech** [comment]
,

**Pull request closed without merging**
